version: 2.1

jobs:    
  syntax_check:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/workspace
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: flake8

workflows:
  version: 2
  hoge:
    jobs:
      - syntax_check
