version: 2.1

orbs:
  # welcome: circleci/welcome-orb@0.4.1
  flake8: arrai/flake8@6.0.0

jobs:    
  syntax_check:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/workspace
    steps:
      - checkout
      - flake8/setup_flake8:
          wd: ~/workspace
      - flake8/flake8_errors:
          wd: ~/workspace/src

workflows:
  version: 2
  hoge:
    jobs:
      - syntax_check
